version: '3'
services:
  app:
    build: .
    ports:
      - "21000:21000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:54321/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword

  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "54321:5432"  # Exposing PostgreSQL on port 54321
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "myuser" ]
        interval: 10s
        retries: 5